---
title: "Combined Stimulus Sets Meta-Awareness"
author: "Adam Barnas"
#date: '`r Sys.Date()`'
date: "Last compiled at `r format(Sys.time(), '%l:%M %p')` on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: show
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: no
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up R environment.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(plyr)
library(magick)
library(png)
library(lme4)
library(lmerTest)
library(irrNA)
library(psy)
library(coefficientalpha)
library(parameters)
```

# Set the R working drectory to the main experiment directory.

```{r message=FALSE}
setwd("/Users/adambarnas/Box/MetaAwareness/data/")  
```

# Read in data files.

```{r warning=FALSE}
rensink_similarity <- list.files(path = "./Rensink_Similarity", pattern = "*.csv", recursive = T, full.names = T, ignore.case = F) %>%
  map_df(~read.csv(., colClasses=c("gender..m.f."="character", "a"="character", "tp_a"="character")))
nrow(rensink_similarity %>% distinct(workerId,.keep_all = FALSE))
rensink_similarity_bad <- rensink_similarity %>% 
  group_by(workerId) %>% 
  #filter(any(catch_same_resp.keys != 6) | any(catch_different_resp.keys != 1))
  filter(any(catch_same_resp.keys != 6))
rensink_bad_workers <- data.frame(unique(rensink_similarity_bad$workerId))
colnames(rensink_bad_workers) <- c("workerId")
write.csv(rensink_bad_workers,'rensink_bad_workers.csv', row.names=FALSE)
rensink_similarity_good <- rensink_similarity %>% 
  group_by(workerId) %>% 
  #filter(any(catch_same_resp.keys == 6) & any(catch_different_resp.keys == 1))
  filter(any(catch_same_resp.keys == 6))
nrow(rensink_similarity_good %>% distinct(workerId,.keep_all = FALSE))
rensink_similarity_images = subset(rensink_similarity_good, select = c(user_resp.keys,database,image,number,workerId))
col_idx <- grep("workerId", names(rensink_similarity_images))
rensink_similarity_images <- rensink_similarity_images[, c(col_idx, (1:ncol(rensink_similarity_images))[-col_idx])]
colnames(rensink_similarity_images) <- c("workerId", "similarity", "database", "image", "number")
rensink_similarity_images <- data.frame(na.omit(rensink_similarity_images))
rensink_similarity_images <- rensink_similarity_images %>%  
    mutate(image = as.character(image))
```

# Image-level.

## Count.

```{r}
rensink_similarity_images_count <- rensink_similarity_images %>% 
  group_by(workerId,image) %>% 
  dplyr::summarize(counts = n()) %>%
  spread(image,counts) %>%
  mutate(sum = rowSums(.[-1], na.rm = TRUE))

rensink_similarity_images_count <- data.frame(count = colSums(rensink_similarity_images_count[,2:49], na.rm = TRUE))
rensink_similarity_images_count <- tibble::rownames_to_column(rensink_similarity_images_count, "image")
rensink_similarity_images_count
```

## Average.

```{r}
rensink_similarity_images_average <- rensink_similarity_images %>%
  group_by(workerId,image) %>%
  dplyr::summarize(average = mean(similarity)) %>%
  spread(image,average) %>% 
  mutate(subj_avg = rowMeans(.[-1], na.rm = TRUE))
mean(rensink_similarity_images_average$subj_avg)

rensink_similarity_images_average <- data.frame(semantic_similarity = colMeans(rensink_similarity_images_average[,2:49], na.rm = TRUE))
rensink_similarity_images_average <- tibble::rownames_to_column(rensink_similarity_images_average, "image")
rensink_similarity_images_average
write.csv(rensink_similarity_images_average,'rensink_semantic_similarity_rating.csv', row.names=FALSE)
```

# Description-level.

## Count.

```{r}
rensink_similarity_images$x <- paste0(rensink_similarity_images$image,"_",rensink_similarity_images$number)
rensink_similarity_descriptions_count <- rensink_similarity_images %>% 
  group_by(workerId,x) %>% 
  dplyr::summarize(counts = n()) %>%
  spread(x,counts) %>%
  mutate(sum = rowSums(.[-1], na.rm = FALSE))

rensink_similarity_descriptions_count <- data.frame(count = colSums(rensink_similarity_descriptions_count[,2:301], na.rm = TRUE))
rensink_similarity_descriptions_count <- tibble::rownames_to_column(rensink_similarity_descriptions_count, "description")
rensink_similarity_descriptions_count

rensink_semantic_final_descriptions <- read_csv("rensink_semantic_final_descriptions.csv")
rensink_semantic_final_descriptions$x <- paste0(rensink_semantic_final_descriptions$image,"_",rensink_semantic_final_descriptions$number)
description = subset(rensink_semantic_final_descriptions, select = c(x))
description$count <- 0
colnames(description) <- c("description", "count")
description <- description %>%  
    mutate(description = as.character(description))
rensink_similarity_descriptions_count <- rbind(description,rensink_similarity_descriptions_count)%>%group_by(description)%>%summarise_each(funs(sum))
rensink_similarity_descriptions_count

rensink_similarity_descriptions_count <- rensink_similarity_descriptions_count %>% 
  arrange(count)
rensink_similarity_descriptions_count
rensink_similarity_descriptions_count$stim_set <- "rensink"
write.csv(rensink_similarity_descriptions_count, 'rensink_similarity_descriptions_count.csv', row.names=FALSE)

rensink_similarity_descriptions_count_needed <- rensink_similarity_descriptions_count %>% 
  filter(count < 3)
rensink_semantic_final_descriptions_partial <- rensink_semantic_final_descriptions[(rensink_semantic_final_descriptions$x %in% rensink_similarity_descriptions_count_needed$description),]
rensink_semantic_final_descriptions_partial = subset(rensink_semantic_final_descriptions_partial, select = -c(x))

write.csv(rensink_semantic_final_descriptions_partial,'rensink_semantic_final_descriptions_partial.csv', row.names=FALSE)
```

## Average.

```{r}
rensink_similarity_descriptions_average <- rensink_similarity_images %>%
  group_by(workerId,x) %>%
  dplyr::summarize(average = mean(similarity)) %>%
  spread(x,average) %>% 
  mutate(subj_avg = rowMeans(.[-1], na.rm = TRUE))
mean(rensink_similarity_descriptions_average$subj_avg)

rensink_similarity_descriptions_average <- data.frame(semantic_similarity = colMeans(rensink_similarity_descriptions_average[,2:301], na.rm = TRUE))
rensink_similarity_descriptions_average <- tibble::rownames_to_column(rensink_similarity_descriptions_average, "image")
rensink_similarity_descriptions_average
```