---
title: "Combined Stimulus Sets Meta-Awareness"
author: "Adam Barnas"
#date: '`r Sys.Date()`'
date: "Last compiled at `r format(Sys.time(), '%l:%M %p')` on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: show
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: no
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up R environment.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(plyr)
library(magick)
library(png)
library(lme4)
library(lmerTest)
library(irrNA)
library(psy)
library(coefficientalpha)
library(parameters)
```

# Set the R working drectory to the main experiment directory.

```{r message=FALSE}
setwd("/Users/adambarnas/Box/MetaAwareness/data/")  
```

# Read in Attempt 1 data files.

```{r warning=FALSE}
wolfe1_semantic <- list.files(path = "./Wolfe1_Semantic/Attempt_1", pattern = "*.csv", full.names = T, ignore.case = F) %>%
  map_df(~read.csv(., colClasses=c("gender..m.f."="character", "a"="character", "tp_a"="character")))
nrow(wolfe1_semantic %>% distinct(workerId,.keep_all = FALSE))
wolfe1_semantic_images = subset(wolfe1_semantic, select = c(trial_response_rt,image_1_text,image_2_text,workerId,image_a))
col_idx <- grep("workerId", names(wolfe1_semantic_images))
wolfe1_semantic_images <- wolfe1_semantic_images[, c(col_idx, (1:ncol(wolfe1_semantic_images))[-col_idx])]
wolfe1_semantic_images <- data.frame(na.omit(wolfe1_semantic_images))
wolfe1_semantic_images <- subset(wolfe1_semantic_images, image_a != "")
wolfe1_semantic_images <- wolfe1_semantic_images %>%
separate(image_a,into=c('database', 'image'), sep = "([\\_])", extra = "merge")
wolfe1_semantic_images$image <- lapply(wolfe1_semantic_images$image, gsub, pattern='-a_w_outline.jpg', replacement='')
colnames(wolfe1_semantic_images) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_images$database <- "wolfe1"
wolfe1_semantic_images <- wolfe1_semantic_images %>%  
    mutate(image = as.character(image))

wolfe1_semantic_cow = subset(wolfe1_semantic, select = c(workerId,Cow_response_rt,Cow_a_text,Cow_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_cow))
wolfe1_semantic_cow <- wolfe1_semantic_cow[, c(col_idx, (1:ncol(wolfe1_semantic_cow))[-col_idx])]
wolfe1_semantic_cow <- data.frame(na.omit(wolfe1_semantic_cow))
wolfe1_semantic_cow$database <- "wolfe1"
wolfe1_semantic_cow$image <- "cow"
colnames(wolfe1_semantic_cow) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_cow <- wolfe1_semantic_cow %>%  
    mutate(image = as.character(image))


wolfe1_semantic_airplane = subset(wolfe1_semantic, select = c(workerId,Airplane_response_rt,Airplane_a_text,Airplane_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_airplane))
wolfe1_semantic_airplane <- wolfe1_semantic_airplane[, c(col_idx, (1:ncol(wolfe1_semantic_airplane))[-col_idx])]
wolfe1_semantic_airplane <- data.frame(na.omit(wolfe1_semantic_airplane))
wolfe1_semantic_airplane$database <- "wolfe1"
wolfe1_semantic_airplane$image <- "airplane"
colnames(wolfe1_semantic_airplane) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_airplane <- wolfe1_semantic_airplane %>%  
    mutate(image = as.character(image))

wolfe1_semantic_final_1 <- rbind(wolfe1_semantic_images, wolfe1_semantic_cow, wolfe1_semantic_airplane)
wolfe1_semantic_final_1 <- wolfe1_semantic_final_1 %>% 
  arrange(workerId)
write.csv(wolfe1_semantic_final_1,'wolfe1_descriptions_attempt_1_w_catch.csv', row.names=FALSE)
```

# Read in Attempt 2 data files.

```{r warning=FALSE}
wolfe1_semantic <- list.files(path = "./Wolfe1_Semantic/Attempt_2", pattern = "*.csv", full.names = T, ignore.case = F) %>%
  map_df(~read.csv(., colClasses=c("gender..m.f."="character", "a"="character", "tp_a"="character")))
nrow(wolfe1_semantic %>% distinct(workerId,.keep_all = FALSE))
wolfe1_semantic_images = subset(wolfe1_semantic, select = c(trial_response_rt,image_1_text,image_2_text,workerId,image_a))
col_idx <- grep("workerId", names(wolfe1_semantic_images))
wolfe1_semantic_images <- wolfe1_semantic_images[, c(col_idx, (1:ncol(wolfe1_semantic_images))[-col_idx])]
wolfe1_semantic_images <- data.frame(na.omit(wolfe1_semantic_images))
wolfe1_semantic_images <- subset(wolfe1_semantic_images, image_a != "")
wolfe1_semantic_images <- wolfe1_semantic_images %>%
separate(image_a,into=c('database', 'image'), sep = "([\\_])", extra = "merge")
wolfe1_semantic_images$image <- lapply(wolfe1_semantic_images$image, gsub, pattern='-a_w_outline.jpg', replacement='')
colnames(wolfe1_semantic_images) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_images$database <- "wolfe1"
wolfe1_semantic_images <- wolfe1_semantic_images %>%  
    mutate(image = as.character(image))

wolfe1_semantic_cow = subset(wolfe1_semantic, select = c(workerId,Cow_response_rt,Cow_a_text,Cow_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_cow))
wolfe1_semantic_cow <- wolfe1_semantic_cow[, c(col_idx, (1:ncol(wolfe1_semantic_cow))[-col_idx])]
wolfe1_semantic_cow <- data.frame(na.omit(wolfe1_semantic_cow))
wolfe1_semantic_cow$database <- "wolfe1"
wolfe1_semantic_cow$image <- "cow"
colnames(wolfe1_semantic_cow) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_cow <- wolfe1_semantic_cow %>%  
    mutate(image = as.character(image))


wolfe1_semantic_airplane = subset(wolfe1_semantic, select = c(workerId,Airplane_response_rt,Airplane_a_text,Airplane_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_airplane))
wolfe1_semantic_airplane <- wolfe1_semantic_airplane[, c(col_idx, (1:ncol(wolfe1_semantic_airplane))[-col_idx])]
wolfe1_semantic_airplane <- data.frame(na.omit(wolfe1_semantic_airplane))
wolfe1_semantic_airplane$database <- "wolfe1"
wolfe1_semantic_airplane$image <- "airplane"
colnames(wolfe1_semantic_airplane) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_airplane <- wolfe1_semantic_airplane %>%  
    mutate(image = as.character(image))

wolfe1_semantic_final_2 <- rbind(wolfe1_semantic_images, wolfe1_semantic_cow, wolfe1_semantic_airplane)
wolfe1_semantic_final_2 <- wolfe1_semantic_final_2 %>% 
  arrange(workerId)
write.csv(wolfe1_semantic_final_2,'wolfe1_descriptions_attempt_2_w_catch.csv', row.names=FALSE)
```

# Read in Attempt 3 data files.

```{r warning=FALSE}
wolfe1_semantic <- list.files(path = "./Wolfe1_Semantic/Attempt_3", pattern = "*.csv", full.names = T, ignore.case = F) %>%
  map_df(~read.csv(., colClasses=c("gender..m.f."="character", "a"="character", "tp_a"="character")))
nrow(wolfe1_semantic %>% distinct(workerId,.keep_all = FALSE))
wolfe1_semantic_images = subset(wolfe1_semantic, select = c(trial_response_rt,image_1_text,image_2_text,workerId,image_a))
col_idx <- grep("workerId", names(wolfe1_semantic_images))
wolfe1_semantic_images <- wolfe1_semantic_images[, c(col_idx, (1:ncol(wolfe1_semantic_images))[-col_idx])]
wolfe1_semantic_images <- data.frame(na.omit(wolfe1_semantic_images))
wolfe1_semantic_images <- subset(wolfe1_semantic_images, image_a != "")
wolfe1_semantic_images <- wolfe1_semantic_images %>%
separate(image_a,into=c('database', 'image'), sep = "([\\_])", extra = "merge")
wolfe1_semantic_images$image <- lapply(wolfe1_semantic_images$image, gsub, pattern='-a_w_outline.jpg', replacement='')
colnames(wolfe1_semantic_images) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_images$database <- "wolfe1"
wolfe1_semantic_images <- wolfe1_semantic_images %>%  
    mutate(image = as.character(image))

wolfe1_semantic_cow = subset(wolfe1_semantic, select = c(workerId,Cow_response_rt,Cow_a_text,Cow_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_cow))
wolfe1_semantic_cow <- wolfe1_semantic_cow[, c(col_idx, (1:ncol(wolfe1_semantic_cow))[-col_idx])]
wolfe1_semantic_cow <- data.frame(na.omit(wolfe1_semantic_cow))
wolfe1_semantic_cow$database <- "wolfe1"
wolfe1_semantic_cow$image <- "cow"
colnames(wolfe1_semantic_cow) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_cow <- wolfe1_semantic_cow %>%  
    mutate(image = as.character(image))


wolfe1_semantic_airplane = subset(wolfe1_semantic, select = c(workerId,Airplane_response_rt,Airplane_a_text,Airplane_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_airplane))
wolfe1_semantic_airplane <- wolfe1_semantic_airplane[, c(col_idx, (1:ncol(wolfe1_semantic_airplane))[-col_idx])]
wolfe1_semantic_airplane <- data.frame(na.omit(wolfe1_semantic_airplane))
wolfe1_semantic_airplane$database <- "wolfe1"
wolfe1_semantic_airplane$image <- "airplane"
colnames(wolfe1_semantic_airplane) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_airplane <- wolfe1_semantic_airplane %>%  
    mutate(image = as.character(image))

wolfe1_semantic_final_3 <- rbind(wolfe1_semantic_images, wolfe1_semantic_cow, wolfe1_semantic_airplane)
wolfe1_semantic_final_3 <- wolfe1_semantic_final_3 %>% 
  arrange(workerId)
write.csv(wolfe1_semantic_final_3,'wolfe1_descriptions_attempt_3_w_catch.csv', row.names=FALSE)
```

# Read in Attempt 4 data files.

```{r warning=FALSE}
wolfe1_semantic <- list.files(path = "./Wolfe1_Semantic/Attempt_4", pattern = "*.csv", full.names = T, ignore.case = F) %>%
  map_df(~read.csv(., colClasses=c("gender..m.f."="character", "a"="character", "tp_a"="character")))
nrow(wolfe1_semantic %>% distinct(workerId,.keep_all = FALSE))
wolfe1_semantic_images = subset(wolfe1_semantic, select = c(trial_response_rt,image_1_text,image_2_text,workerId,image_a))
col_idx <- grep("workerId", names(wolfe1_semantic_images))
wolfe1_semantic_images <- wolfe1_semantic_images[, c(col_idx, (1:ncol(wolfe1_semantic_images))[-col_idx])]
wolfe1_semantic_images <- data.frame(na.omit(wolfe1_semantic_images))
wolfe1_semantic_images <- subset(wolfe1_semantic_images, image_a != "")
wolfe1_semantic_images <- wolfe1_semantic_images %>%
separate(image_a,into=c('database', 'image'), sep = "([\\_])", extra = "merge")
wolfe1_semantic_images$image <- lapply(wolfe1_semantic_images$image, gsub, pattern='-a_w_outline.jpg', replacement='')
colnames(wolfe1_semantic_images) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_images$database <- "wolfe1"
wolfe1_semantic_images <- wolfe1_semantic_images %>%  
    mutate(image = as.character(image))

wolfe1_semantic_cow = subset(wolfe1_semantic, select = c(workerId,Cow_response_rt,Cow_a_text,Cow_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_cow))
wolfe1_semantic_cow <- wolfe1_semantic_cow[, c(col_idx, (1:ncol(wolfe1_semantic_cow))[-col_idx])]
wolfe1_semantic_cow <- data.frame(na.omit(wolfe1_semantic_cow))
wolfe1_semantic_cow$database <- "wolfe1"
wolfe1_semantic_cow$image <- "cow"
colnames(wolfe1_semantic_cow) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_cow <- wolfe1_semantic_cow %>%  
    mutate(image = as.character(image))


wolfe1_semantic_airplane = subset(wolfe1_semantic, select = c(workerId,Airplane_response_rt,Airplane_a_text,Airplane_b_text))
col_idx <- grep("workerId", names(wolfe1_semantic_airplane))
wolfe1_semantic_airplane <- wolfe1_semantic_airplane[, c(col_idx, (1:ncol(wolfe1_semantic_airplane))[-col_idx])]
wolfe1_semantic_airplane <- data.frame(na.omit(wolfe1_semantic_airplane))
wolfe1_semantic_airplane$database <- "wolfe1"
wolfe1_semantic_airplane$image <- "airplane"
colnames(wolfe1_semantic_airplane) <- c("workerId", "RT", "image_1_text", "image_2_text", "database", "image")
wolfe1_semantic_airplane <- wolfe1_semantic_airplane %>%  
    mutate(image = as.character(image))

wolfe1_semantic_final_4 <- rbind(wolfe1_semantic_images, wolfe1_semantic_cow, wolfe1_semantic_airplane)
wolfe1_semantic_final_4 <- wolfe1_semantic_final_4 %>% 
  arrange(workerId)
write.csv(wolfe1_semantic_final_4,'wolfe1_descriptions_attempt_4_w_catch.csv', row.names=FALSE)
```

# Combine data files.

```{r}
wolfe1_semantic_all<- rbind(wolfe1_semantic_final_1, wolfe1_semantic_final_2, wolfe1_semantic_final_3, wolfe1_semantic_final_4)
wolfe1_semantic_all <- wolfe1_semantic_all %>% 
  filter(image != 'airplane' & image != 'cow')

wolfe1_semantic_all_count <- wolfe1_semantic_all %>% 
  group_by(workerId,image) %>% 
  dplyr::summarize(counts = n()) %>%
  spread(image,counts) %>%
  mutate(sum = rowSums(.[-1], na.rm = TRUE))

wolfe1_semantic_all_count <- data.frame(count = colSums(wolfe1_semantic_all_count[,2:112], na.rm = TRUE))
wolfe1_semantic_all_count <- tibble::rownames_to_column(wolfe1_semantic_all_count, "image")
wolfe1_semantic_all_count
```

# Filter good subjects.

```{r message=FALSE}
wolfe1_semantic_good <- read_csv("Wolfe1_Semantic_good.csv")
wolfe1_semantic_final_descriptions <- wolfe1_semantic_all %>% 
      filter(wolfe1_semantic_all$workerId %in% wolfe1_semantic_good$workerId)
nrow(wolfe1_semantic_final_descriptions %>% distinct(workerId,.keep_all = FALSE))

wolfe1_semantic_final_descriptions_count <- wolfe1_semantic_final_descriptions %>% 
  group_by(workerId,image) %>% 
  dplyr::summarize(counts = n()) %>%
  spread(image,counts) %>%
  mutate(sum = rowSums(.[-1], na.rm = TRUE))

wolfe1_semantic_final_descriptions_count <- data.frame(count = colSums(wolfe1_semantic_final_descriptions_count[,2:112], na.rm = TRUE))
wolfe1_semantic_final_descriptions_count <- tibble::rownames_to_column(wolfe1_semantic_final_descriptions_count, "image")
wolfe1_semantic_final_descriptions_count
wolfe1_semantic_final_descriptions_count <- wolfe1_semantic_final_descriptions_count %>% 
  arrange(count)
wolfe1_semantic_final_descriptions_count
wolfe1_semantic_final_descriptions_count$stim_set <- "wolfe1"
write.csv(wolfe1_semantic_final_descriptions_count, 'wolfe1_semantic_final_descriptions_count.csv', row.names=FALSE)

wolfe1_semantic_final_descriptions <- wolfe1_semantic_final_descriptions[, -c(1,2)]
wolfe1_semantic_final_descriptions <- wolfe1_semantic_final_descriptions %>% 
  arrange(image)
wolfe1_semantic_final_descriptions$number <- ave(wolfe1_semantic_final_descriptions$image_1_text, wolfe1_semantic_final_descriptions$image, FUN = seq_along)
write.csv(wolfe1_semantic_final_descriptions,'wolfe1_semantic_final_descriptions.csv', row.names=FALSE)
```